import type { Metadata } from 'next';
import { RootLayoutBoilerplate } from '@/boilerplate/kits/RootLayout';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default RootLayoutBoilerplate;
